services:
  - type: web
    name: eventcraft-pro
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 120 --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - key: SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eventcraft-db
          property: connectionString
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: eventcraft-db
    databaseName: eventcraft
    user: eventcraft_user
    plan: free
    ipAllowList: []
